L'api des images, j'ai mis à jour le run et j'ai modifié la table Ima…
hamzaoui12/projet_pro pull request #119
Opened 2023-05-25 12:47 UTC by NoraSEDJAI

…ge en changant le type de picture (blob) par text. Je peux desormais supprimer, ajouter, modifier, lire les images.

2023-05-27 00:37 UTC, sckaper requested changes
Il faudrait que l'api puisse prendre des images et non du texte, je ne peux pas valider les url

2023-05-27 08:43 UTC, NoraSEDJAI commented
Ok, je vais corriger ça.

2023-05-31 19:25 UTC, NoraSEDJAI commented
![image](https://github.com/hamzaoui12/projet_pro/assets/87068779/25149296-7520-4513-9e85-a081b5aea9c6)
![image](https://github.com/hamzaoui12/projet_pro/assets/87068779/a07bf619-d0cc-44e3-b077-2992f194cd77)

2023-06-09 07:20 UTC, sckaper reviewed
Certaines parties de code importantes ont été supprimées...
Je pense qu'il faudrait que tu revert et que tu commit sans la partie front et sans suppression de lignes

2023-06-09 09:28 UTC, closed without merging