Update code api material
hamzaoui12/projet_pro pull request #98
Opened 2023-05-20 12:31 UTC by NoraSEDJAI

2023-05-20 14:16 UTC, sckaper requested changes
Enlève le .env, prend le temps de regarder ce que tu commit

2023-05-27 00:35 UTC, sckaper reviewed
Tu n'as pas fait le revert

2023-05-27 13:59 UTC, NoraSEDJAI commented
C'est bon Eric, il n'y a plus les fichiers .env, PictureModels et routeModels dans l'historique.

2023-05-28 13:19 UTC, sckaper approved these changes
Tout me semble bon

2023-05-28 13:32 UTC, merged